### ISSUE TITLE
modest (very modest) patch proposal

### ISSUE THREAD

**Issue by icastang** [jzy3d/bigpicture#3] opened 2020-06-13 14:32 UTC
This is patch to :

- make the maven build work (by adding some repository).
- make a small change on one example to "make it look" better.

anyway not even sure those changes make sense or that anyone is even listening ...

[0001-This-is-a-commit-from-a-git-jzy3d-maven-noob.patch.zip](https://github.com/jzy3d/bigpicture/files/4774794/0001-This-is-a-commit-from-a-git-jzy3d-maven-noob.patch.zip)

**Comment by jzy3d** [comment] 2020-06-15 22:38
Thank you for contributing! This would be easier to include through a merge request.

Could you clarify which dependency is resolved by adding sonatype repo? Also, do not hesitate to add a picture to this discussion showing how your small change make the chart "look better".

**Comment by icastang** [comment] 2020-06-16 06:31
Hello,

1) regarding the change on the example, what happens is that with current master, there is one
"artifact line" in the y=0 plane, that messes up the scale, we end up not seeing the scatter points at all in the other plane of the demo (y=1, y=2, y=..) see screenshots for a better idea.

![current_master](https://user-images.githubusercontent.com/66876422/84737979-50506000-afa9-11ea-8de0-ad7644ac674c.png)

![with_change](https://user-images.githubusercontent.com/66876422/84737977-4dee0600-afa9-11ea-88c5-3041dddfb666.png)
 

2) regarding the build change

If I try to build bigpicture maven fails to find **org.jzy3d:jzy3d-api:jar:1.0.3-SNAPSHOT,org.jzy3d:jzy3d-javafx:jar:1.0.3-SNAPSHOT**
that is why I had added the sonatype repo, however as I was trying to reproduce the build it now fails even with sonatype repo ( I don't know why)

The workaround I found, is to first build the whole jzy3d-api on my machine (so that the missing jars are in my local repo), then the build of bigpicture  works without any need to change the pom.xml.

here is the error when building bigpicture without first building jzy3d-api
`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10:14 min
[INFO] Finished at: 2020-06-16T07:16:09+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jzy3d-bigpicture: Could not resolve dependencies for project org.jzy3d:jzy3d-bigpicture:jar:1.0.3-SNAPSHOT: The following artifacts could not be resolved: org.jzy3d:jzy3d-api:jar:1.0.3-SNAPSHOT, org.jzy3d:jzy3d-javafx:jar:1.0.3-SNAPSHOT: Could not find artifact org.jzy3d:jzy3d-api:jar:1.0.3-SNAPSHOT in Spark repository (http://www.sparkjava.com/nexus/content/repositories/spark/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
`

Thanks for taking the time to answer and for your work on jzy3d

**Comment by jzy3d** [comment] 2020-06-16 07:30
Thank you.

Indeed the first line is an identity row that mess up the scale by adding a value that is much larger than the generated values.

Concerning the build you are right. Sonatype do not provide any jzy3d jar (yet). The problem is that the pom file refer to the old maven repo of jzy3d. If you replace `http://www.jzy3d.org/maven/` by `http://maven.jzy3d.org/` then your build should run properly as the later provides version 1.0.3-SNAPSHOT.

**Closed** 2020-06-16 07:44 UTC

**Comment by jzy3d** [comment] 2020-06-16 07:45
I needed to make the fix on my machine to ensure I wasn't wrong, so you just have to pull again the source, no need to push your changes.

Thanks again for contributing!
